export default {

  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT',

  LOGIN_REQUIRED: 'LOGIN_REQUIRED',

  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  CURRENT_USER: 'CURRENT_USER',

  OPEN_ADD_CHANNEL_FORM: 'OPEN_ADD_CHANNEL_FORM',
  CLOSE_ADD_CHANNEL_FORM: 'CLOSE_ADD_CHANNEL_FORM',

  ADD_CHANNEL: 'ADD_CHANNEL',
  ADD_CHANNEL_SUCCESS: 'ADD_CHANNEL_SUCCESS',
  ADD_CHANNEL_FAILURE: 'ADD_CHANNEL_FAILURE',

  SHOW_PODCAST_DETAIL: 'SHOW_PODCAST_DETAIL',
  HIDE_PODCAST_DETAIL: 'HIDE_PODCAST_DETAIL',

  SEARCH: 'SEARCH',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAILURE: 'SEARCH_FAILURE',

  LATEST_PODCASTS_SUCCESS: 'LATEST_PODCASTS_SUCCESS',
  LATEST_PODCASTS_FAILURE: 'LATEST_PODCASTS_FAILURE',

  CURRENTLY_PLAYING: 'CURRENTLY_PLAYING',

  GET_CHANNELS_SUCCESS: 'GET_CHANNELS_SUCCESS',
  GET_CHANNELS_FAILURE: 'GET_CHANNELS_FAILURE',

  GET_CHANNEL_SUCCESS: 'GET_CHANNEL_SUCCESS',
  GET_CHANNEL_FAILURE: 'GET_CHANNEL_FAILURE',

  ADD_ALERT: 'ADD_ALERT',
  DISMISS_ALERT: 'DISMISS_ALERT',

  SUBSCRIBE: 'SUBSCRIBE',
  UNSUBSCRIBE: 'UNSUBSCRIBE',

  GET_BOOKMARKS_SUCCESS: 'GET_BOOKMARKS_SUCCESS',
  GET_BOOKMARKS_FAILURE: 'GET_BOOKMARKS_FAILURE',

  ADD_BOOKMARK: 'ADD_BOOKMARK',
  DELETE_BOOKMARK: 'DELETE_BOOKMARK',

  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  OPEN_RECOVER_PASSWORD_FORM: 'OPEN_RECOVER_PASSWORD_FORM',
  CLOSE_RECOVER_PASSWORD_FORM: 'CLOSE_RECOVER_PASSWORD_FORM',
  
  RECOVER_PASSWORD_SUCCESS: 'RECOVER_PASSWORD_SUCCESS',
  RECOVER_PASSWORD_FAILURE: 'RECOVER_PASSWORD_FAILURE',

  CHANGE_EMAIL_SUCCESS: 'CHANGE_EMAIL_SUCCESS',
  CHANGE_EMAIL_FAILURE: 'CHANGE_EMAIL_FAILURE'
};
