export default {

  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT',

  LOGIN_REQUIRED: 'LOGIN_REQUIRED',

  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  CURRENT_USER_SUCCESS: 'CURRENT_USER_SUCCESS',
  CURRENT_USER_FAILURE: 'CURRENT_USER_FAILURE',

  OPEN_ADD_CHANNEL_FORM: 'OPEN_ADD_CHANNEL_FORM',
  CLOSE_ADD_CHANNEL_FORM: 'CLOSE_ADD_CHANNEL_FORM',
  ADD_CHANNEL: 'ADD_CHANNEL',
  ADD_CHANNEL_SUCCESS: 'ADD_CHANNEL_SUCCESS',
  ADD_CHANNEL_FAILURE: 'ADD_CHANNEL_FAILURE',

  SEARCH: 'SEARCH'
};
